# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d176bddd87dbf81e7df3da5ac85cd1596e6b4ad409eea0597f38e9f38bcbf5d442ca7f70c29985637576f78805d216923ab6f94e3313577d09ec9c0ff00fe59

test:
  secret_key_base: 450cadb3a7508082a441d8fb770b2e8f9b87fac3d7cac0d0b631a276689c0f21079fda1f2c5fe65834cadda6423d8d7bbc8609870ad38bec08d57b632e36b3e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
